# Target time in milliseconds since Unix Epoch (https://currentmillis.com/)
target: 1735339500000
triggers:
  100000000:
    - "say This will be called once and for sure, you can initialize scoreboards and stuff here"
  -100000000:
    - "say &3%countdown% seconds left!" # & character is used for color, and %countdown% for the countdown in seconds
  60:
    - "say &4Last %countdown% seconds!"
  30:
    - "say &4&bLAST %countdown% SECONDS!"
  -10:
    - "say &6%countdown%!"
    - "give @a minecraft:diamond"
  0:
    - "say &7OLEY!"

bossbars:
  60: # Remaining time (in seconds)
    Title: "&b1 minute remaining!" # BossBar title
    Progress: 0.0 # BossBar fill level (0.0 - 1.0)
    Color: WHITE # BossBar color (RED, BLUE, GREEN, etc.)
    Style: SEGMENTED_10 # BossBar style (SOLID, SEGMENTED_6, SEGMENTED_10, etc.)
  30:
    Title: "&b30 seconds left!"
    Progress: 0.5
    Color: WHITE
    Style: SEGMENTED_10
  0:
    Title: "&bHappy New Year!"
    Progress: 1.0
    Color: WHITE
    Style: SEGMENTED_10